-- 코드를 입력하세요
SELECT A.AUTHOR_ID,A.AUTHOR_NAME,B.CATEGORY, SUM(B.PRICE*S.SALES) AS SALES
FROM BOOK AS B
JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES AS S ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE LIKE '2022-01%'
GROUP  BY A.AUTHOR_ID,A.AUTHOR_NAME, B.CATEGORY
ORDER BY 1, 3 DESC;