-- 코드를 작성해주세요

SELECT E3.ID
FROM ECOLI_DATA AS E1 
LEFT JOIN ECOLI_DATA AS E2 ON E1.ID=E2.PARENT_ID
LEFT JOIN ECOLI_DATA AS E3 ON E2.ID=E3.PARENT_ID
WHERE E1.PARENT_ID IS NULL AND E3.ID IS NOT NULL
ORDER BY 1