WITH TEMP AS(
    SELECT ID, NTILE(4) OVER(ORDER BY SIZE_OF_COLONY) AS SIZE
    FROM ECOLI_DATA
)

SELECT ID, CASE WHEN SIZE =1 THEN 'LOW'
                WHEN SIZE =2 THEN 'MEDIUM'
                WHEN SIZE =3 THEN 'HIGH'
                ELSE  'CRITICAL' END AS COLONY_NAME
FROM TEMP
ORDER BY 1