-- 코드를 입력하세요
WITH AVGREVIEW AS(
SELECT I.REST_ID, AVG(COALESCE(R.REVIEW_SCORE,0)) AS SCORE
FROM REST_INFO AS I
JOIN REST_REVIEW AS R ON I.REST_ID=R.REST_ID
WHERE I.ADDRESS LIKE '서울%'
GROUP BY I.REST_ID
)
SELECT I.REST_ID, I.REST_NAME,I.FOOD_TYPE,I.FAVORITES,I.ADDRESS,ROUND(A.SCORE,2) AS SCORE
FROM REST_INFO AS I
JOIN AVGREVIEW AS A ON I.REST_ID=A.REST_ID
ORDER BY SCORE DESC, I.FAVORITES DESC;