SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, U.GENDER, COUNT(DISTINCT U.USER_ID) AS USERS
FROM ONLINE_SALE AS O
JOIN USER_INFO AS U ON O.USER_ID=U.USER_ID
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), U.GENDER
HAVING COUNT(U.GENDER)>=1
ORDER BY 1,2,3