WITH MEMBER_CNT AS(
    SELECT MEMBER_ID, COUNT(*) AS CNT
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
)


SELECT I.MEMBER_NAME, R.REVIEW_TEXT,DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS I
JOIN REST_REVIEW AS R ON I.MEMBER_ID = R.MEMBER_ID
JOIN MEMBER_CNT AS C ON I.MEMBER_ID = C.MEMBER_ID
WHERE C.CNT = (SELECT MAX(CNT) FROM MEMBER_CNT)
ORDER BY 3,2

