WITH YEAR_MAX AS(
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
FROM ECOLI_DATA
GROUP BY YEAR
)

SELECT M.YEAR, M.MAX_SIZE-D.SIZE_OF_COLONY AS YEAR_DEV, D.ID
FROM ECOLI_DATA AS D
LEFT JOIN YEAR_MAX AS M ON YEAR(D.DIFFERENTIATION_DATE)=M.YEAR
ORDER BY M.YEAR ASC, YEAR_DEV ASC;
    