-- 코드를 작성해주세요
WITH MAX_ AS (
SELECT I.ID, N.FISH_NAME,I.LENGTH,MAX(LENGTH) OVER(PARTITION BY I.FISH_TYPE) AS MAX_LENGTH
FROM FISH_INFO AS I
LEFT JOIN FISH_NAME_INFO AS N ON I.FISH_TYPE=N.FISH_TYPE
)
SELECT ID,FISH_NAME,LENGTH
FROM MAX_
WHERE LENGTH=MAX_LENGTH
ORDER BY 1