-- 코드를 작성해주세요
SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO,E.EMP_NAME,E.POSITION,E.EMAIL
FROM HR_EMPLOYEES AS E JOIN HR_DEPARTMENT AS D ON E.DEPT_ID = D.DEPT_ID
    JOIN HR_GRADE AS G ON E.EMP_NO = G.EMP_NO
WHERE G.YEAR=2022
GROUP BY E.EMP_NO
ORDER BY 1 DESC
LIMIT 1