SELECT CONCAT('/home/grep/src/',b.board_id,'/',f.file_id,F.FILE_NAME,f.file_ext) as FILE_PATH
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_FILE AS F ON B.BOARD_ID = F.BOARD_ID
WHERE B.VIEWS IN (
    SELECT MAX(VIEWS) 
    FROM USED_GOODS_BOARD
)
ORDER BY F.FILE_ID desc