WITH FRONT AS (
    SELECT SUM(CODE) AS FC FROM SKILLCODES WHERE CATEGORY = 'Front End'
),
PYTHON AS (
    SELECT CODE AS PC FROM SKILLCODES WHERE NAME = 'Python'
),
CS AS (
    SELECT CODE AS CSC FROM SKILLCODES WHERE NAME = 'C#'
)

SELECT IF(SKILL_CODE & FC !=0 AND SKILL_CODE & PC !=0,'A',
          IF(SKILL_CODE & CSC !=0 , 'B', IF(SKILL_CODE & FC != 0,'C',NULL))) AS GRADE, ID, EMAIL
FROM DEVELOPERS JOIN FRONT JOIN PYTHON JOIN CS
HAVING GRADE IS NOT NULL
ORDER BY 1,2